<?php
/**
 * Compliance document generators: VDP, CycloneDX SBOM, conformity declaration
 * and a printable compliance report. Printable HTML only, no FPDF.
 *
 * @package Nubivio_HSH
 */

if (!defined('ABSPATH')) {
    exit;
}

class Nubivio_HSH_Docs {

    /** @var Nubivio_HSH */
    private $core;

    public function __construct($core) {
        $this->core = $core;
    }

    /**
     * Stream a document by type, then the caller exits.
     *
     * @param string $type One of vdp|sbom|conformity|report.
     */
    public function stream($type) {
        switch ($type) {
            case 'vdp':
                $this->stream_vdp();
                break;
            case 'sbom':
                $this->stream_sbom();
                break;
            case 'conformity':
                $this->stream_conformity();
                break;
            case 'report':
                $this->stream_report();
                break;
            default:
                wp_die(esc_html__('Unknown document type.', 'nubivio-healthcare-security-hardening'));
        }
    }

    /* Helpers */

    private function site_name() {
        return get_bloginfo('name');
    }

    private function site_url() {
        return home_url('/');
    }

    private function contact() {
        $o = $this->core->get_options();
        $first = trim((string) $o['sectxt_contacts']);
        if ($first === '') {
            return get_option('admin_email');
        }
        $lines = preg_split('/[\r\n]+/', $first);
        return trim((string) $lines[0]);
    }

    private function html_head($title) {
        return '<!DOCTYPE html><html><head><meta charset="utf-8">'
            . '<meta name="viewport" content="width=device-width, initial-scale=1">'
            . '<title>' . esc_html($title) . '</title>'
            . '<style>'
            . 'body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#231F20;max-width:820px;margin:32px auto;padding:0 24px;line-height:1.55;}'
            . 'h1{color:#13274C;font-size:24px;margin-bottom:4px;}h2{color:#044172;font-size:17px;margin-top:28px;border-bottom:1px solid #E6E7E8;padding-bottom:6px;}'
            . 'table{border-collapse:collapse;width:100%;margin:12px 0;}th,td{border:1px solid #E6E7E8;padding:8px 10px;text-align:left;font-size:13px;vertical-align:top;}'
            . 'th{background:#F5F7F9;}.muted{color:#6F727A;font-size:12px;}.pass{color:#0c7a4f;font-weight:700;}.fail{color:#b3261e;font-weight:700;}.warn{color:#9a6a16;font-weight:700;}'
            . '.print-hint{background:#D9E2EB;color:#044172;padding:10px 14px;border-radius:8px;font-size:13px;margin:16px 0;}'
            . '@media print{.print-hint{display:none;}}'
            . '</style></head><body>';
    }

    private function html_foot() {
        return '<p class="muted">' . esc_html(sprintf(
            /* translators: 1: site name, 2: date. */
            __('Generated by Nubivio Healthcare Security Hardening for %1$s on %2$s.', 'nubivio-healthcare-security-hardening'),
            $this->site_name(),
            gmdate('Y-m-d')
        )) . '</p></body></html>';
    }

    private function print_hint() {
        return '<div class="print-hint">' . esc_html__('Tip: use your browser Print function and choose Save as PDF to keep a copy.', 'nubivio-healthcare-security-hardening') . '</div>';
    }

    private function send_html_headers() {
        if (!headers_sent()) {
            header('Content-Type: text/html; charset=utf-8');
            header('X-Robots-Tag: noindex');
        }
    }

    /* VDP */

    private function stream_vdp() {
        $o = $this->core->get_options();
        $this->send_html_headers();

        echo $this->html_head(__('Vulnerability Disclosure Policy', 'nubivio-healthcare-security-hardening')); // phpcs:ignore WordPress.Security.EscapeOutput
        echo $this->print_hint(); // phpcs:ignore WordPress.Security.EscapeOutput
        echo '<h1>' . esc_html__('Vulnerability Disclosure Policy', 'nubivio-healthcare-security-hardening') . '</h1>';
        echo '<p class="muted">' . esc_html($this->site_name()) . ' - ' . esc_html($this->site_url()) . '</p>';

        echo '<h2>' . esc_html__('Introduction', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<p>' . esc_html__('We take the security of our systems seriously and we value the security community. The responsible disclosure of security vulnerabilities helps us keep our users safe. This policy sets out how to report vulnerabilities to us.', 'nubivio-healthcare-security-hardening') . '</p>';

        echo '<h2>' . esc_html__('How to report', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<p>' . esc_html__('Please send reports to the contact below.', 'nubivio-healthcare-security-hardening') . '</p>';
        echo '<p><strong>' . esc_html__('Contact:', 'nubivio-healthcare-security-hardening') . '</strong> ' . esc_html($this->contact()) . '</p>';

        if (trim((string) $o['sectxt_policy']) !== '') {
            echo '<p><strong>' . esc_html__('Policy reference:', 'nubivio-healthcare-security-hardening') . '</strong> <a href="' . esc_url($o['sectxt_policy']) . '">' . esc_html($o['sectxt_policy']) . '</a></p>';
        }
        if (trim((string) $o['sectxt_ack']) !== '') {
            echo '<p><strong>' . esc_html__('Acknowledgments:', 'nubivio-healthcare-security-hardening') . '</strong> <a href="' . esc_url($o['sectxt_ack']) . '">' . esc_html($o['sectxt_ack']) . '</a></p>';
        }

        echo '<h2>' . esc_html__('Our commitment', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<ul>';
        echo '<li>' . esc_html__('We will acknowledge receipt of your report in a timely manner.', 'nubivio-healthcare-security-hardening') . '</li>';
        echo '<li>' . esc_html__('We will keep you informed of our progress.', 'nubivio-healthcare-security-hardening') . '</li>';
        echo '<li>' . esc_html__('We will not take legal action against researchers who act in good faith and follow this policy.', 'nubivio-healthcare-security-hardening') . '</li>';
        echo '</ul>';

        echo '<h2>' . esc_html__('Scope', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<p>' . esc_html(sprintf(
            /* translators: %s: site URL. */
            __('This policy applies to the public web property at %s. This document supports the vulnerability disclosure requirements of the EU Cyber Resilience Act, Article 14.', 'nubivio-healthcare-security-hardening'),
            $this->site_url()
        )) . '</p>';

        echo $this->html_foot(); // phpcs:ignore WordPress.Security.EscapeOutput
    }

    /* SBOM */

    private function stream_sbom() {
        if (!function_exists('get_plugins')) {
            require_once ABSPATH . 'wp-admin/includes/plugin.php';
        }

        $components = array();

        // WordPress core.
        $components[] = array(
            'type'    => 'application',
            'name'    => 'wordpress',
            'version' => (string) get_bloginfo('version'),
            'purl'    => 'pkg:wordpress/wordpress@' . rawurlencode((string) get_bloginfo('version')),
        );

        // Active plugins.
        foreach (get_plugins() as $file => $data) {
            if (!is_plugin_active($file)) {
                continue;
            }
            $slug = strpos($file, '/') !== false ? explode('/', $file)[0] : basename($file, '.php');
            $ver  = isset($data['Version']) ? $data['Version'] : '0.0.0';
            $components[] = array(
                'type'    => 'library',
                'name'    => isset($data['Name']) ? $data['Name'] : $slug,
                'version' => (string) $ver,
                'purl'    => 'pkg:wordpress/' . rawurlencode($slug) . '@' . rawurlencode((string) $ver),
            );
        }

        // Active theme.
        $theme = wp_get_theme();
        if ($theme && $theme->exists()) {
            $components[] = array(
                'type'    => 'library',
                'name'    => (string) $theme->get('Name'),
                'version' => (string) $theme->get('Version'),
                'purl'    => 'pkg:wordpress/' . rawurlencode((string) $theme->get_stylesheet()) . '@' . rawurlencode((string) $theme->get('Version')),
            );
        }

        $bom = array(
            'bomFormat'    => 'CycloneDX',
            'specVersion'  => '1.5',
            'version'      => 1,
            'metadata'     => array(
                'timestamp' => gmdate('Y-m-d\TH:i:s\Z'),
                'component' => array(
                    'type'    => 'application',
                    'name'    => $this->site_name(),
                    'version' => (string) get_bloginfo('version'),
                ),
            ),
            'components'   => $components,
        );

        if (!headers_sent()) {
            header('Content-Type: application/json; charset=utf-8');
            header('Content-Disposition: attachment; filename=sbom.json');
            header('X-Robots-Tag: noindex');
        }
        echo wp_json_encode($bom, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES); // phpcs:ignore WordPress.Security.EscapeOutput
    }

    /* Conformity declaration */

    private function stream_conformity() {
        $this->send_html_headers();
        echo $this->html_head(__('Conformity self-assessment declaration', 'nubivio-healthcare-security-hardening')); // phpcs:ignore WordPress.Security.EscapeOutput
        echo $this->print_hint(); // phpcs:ignore WordPress.Security.EscapeOutput
        echo '<h1>' . esc_html__('Conformity self-assessment declaration', 'nubivio-healthcare-security-hardening') . '</h1>';
        echo '<p class="muted">' . esc_html($this->site_name()) . ' - ' . esc_html($this->site_url()) . ' - ' . esc_html(gmdate('Y-m-d')) . '</p>';
        echo '<p><strong>' . esc_html__('Contact:', 'nubivio-healthcare-security-hardening') . '</strong> ' . esc_html($this->contact()) . '</p>';
        echo '<p class="muted">' . esc_html__('This is a self-assessment, not a certification. It records the current posture of the public web property and is intended as a starting point for a formal compliance programme.', 'nubivio-healthcare-security-hardening') . '</p>';

        $sections = array(
            'CRA' => __('EU Cyber Resilience Act (CRA)', 'nubivio-healthcare-security-hardening'),
            'GDPR' => __('General Data Protection Regulation (GDPR)', 'nubivio-healthcare-security-hardening'),
            'NIS2' => __('NIS2 Directive (Art. 21)', 'nubivio-healthcare-security-hardening'),
            'NEN7510' => __('NEN 7510 (Dutch healthcare information security)', 'nubivio-healthcare-security-hardening'),
        );
        $notes = array(
            'CRA' => __('A vulnerability disclosure contact is published via security.txt (RFC 9116), supporting Article 14 coordinated disclosure.', 'nubivio-healthcare-security-hardening'),
            'GDPR' => __('Transport encryption and browser protections are enforced. Data minimisation is supported through Referrer-Policy and third-party script control.', 'nubivio-healthcare-security-hardening'),
            'NIS2' => __('Technical measures under Article 21 are assessed, including encryption in transit, backups, access control and logging.', 'nubivio-healthcare-security-hardening'),
            'NEN7510' => __('Web hardening measures relevant to Dutch healthcare information security are documented, as a building block within a wider NEN 7510 programme.', 'nubivio-healthcare-security-hardening'),
        );

        foreach ($sections as $key => $title) {
            echo '<h2>' . esc_html($title) . '</h2>';
            echo '<p>' . esc_html($notes[$key]) . '</p>';
        }

        echo $this->html_foot(); // phpcs:ignore WordPress.Security.EscapeOutput
    }

    /* Report */

    private function stream_report() {
        $this->send_html_headers();
        $scan = $this->core->get_scan();

        echo $this->html_head(__('Compliance report', 'nubivio-healthcare-security-hardening')); // phpcs:ignore WordPress.Security.EscapeOutput
        echo $this->print_hint(); // phpcs:ignore WordPress.Security.EscapeOutput
        echo '<h1>' . esc_html__('Compliance report', 'nubivio-healthcare-security-hardening') . '</h1>';
        echo '<p class="muted">' . esc_html($this->site_name()) . ' - ' . esc_html($this->site_url()) . ' - ' . esc_html(gmdate('Y-m-d')) . '</p>';

        if (!$scan) {
            echo '<p>' . esc_html__('No scan data yet. Run a compliance scan first, then generate this report.', 'nubivio-healthcare-security-hardening') . '</p>';
            echo $this->html_foot(); // phpcs:ignore WordPress.Security.EscapeOutput
            return;
        }

        $band_label = $this->band_label($scan['band']);
        echo '<h2>' . esc_html__('Score', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<p><strong>' . (int) $scan['score'] . ' / 100</strong> (' . esc_html($band_label) . ')</p>';

        // Per-framework findings.
        echo '<h2>' . esc_html__('Findings by framework', 'nubivio-healthcare-security-hardening') . '</h2>';
        $names = array(
            'cra'  => __('CRA (plugin readiness)', 'nubivio-healthcare-security-hardening'),
            'gdpr' => __('GDPR', 'nubivio-healthcare-security-hardening'),
            'nis2' => __('NIS2 Art. 21', 'nubivio-healthcare-security-hardening'),
        );
        foreach ($names as $key => $label) {
            if (empty($scan['frameworks'][$key]['findings'])) {
                continue;
            }
            echo '<h3>' . esc_html($label) . '</h3><table><tr><th>' . esc_html__('Severity', 'nubivio-healthcare-security-hardening') . '</th><th>' . esc_html__('Finding', 'nubivio-healthcare-security-hardening') . '</th></tr>';
            foreach ($scan['frameworks'][$key]['findings'] as $f) {
                echo '<tr><td>' . esc_html(strtoupper((string) $f['severity'])) . '</td><td>' . esc_html((string) $f['message']) . '</td></tr>';
            }
            echo '</table>';
        }

        // Header evidence.
        echo '<h2>' . esc_html__('Header evidence', 'nubivio-healthcare-security-hardening') . '</h2>';
        $scanner = $this->core->scanner();
        $probe = $scanner ? $scanner->probe_headers() : array('ok' => false, 'present' => array());
        if (empty($probe['ok'])) {
            echo '<p class="muted">' . esc_html__('Live verification was unavailable; showing configured headers.', 'nubivio-healthcare-security-hardening') . '</p>';
        }
        echo '<table><tr><th>' . esc_html__('Header', 'nubivio-healthcare-security-hardening') . '</th><th>' . esc_html__('Status', 'nubivio-healthcare-security-hardening') . '</th></tr>';
        foreach ($this->core->preview_headers() as $name => $val) {
            if (!empty($probe['ok'])) {
                $sent = isset($probe['present'][strtolower($name)]);
                $st = $sent ? '<span class="pass">' . esc_html__('sent', 'nubivio-healthcare-security-hardening') . '</span>' : '<span class="fail">' . esc_html__('missing', 'nubivio-healthcare-security-hardening') . '</span>';
            } else {
                $st = '<span class="warn">' . esc_html__('configured', 'nubivio-healthcare-security-hardening') . '</span>';
            }
            echo '<tr><td>' . esc_html($name) . '</td><td>' . $st . '</td></tr>'; // phpcs:ignore WordPress.Security.EscapeOutput
        }
        echo '</table>';

        // security.txt evidence.
        echo '<h2>' . esc_html__('security.txt evidence', 'nubivio-healthcare-security-hardening') . '</h2>';
        $status = $this->core->security_txt_status();
        echo '<p>' . esc_html(sprintf(
            /* translators: %s: mode/status text. */
            __('Mode: %s', 'nubivio-healthcare-security-hardening'),
            $status['mode']
        )) . '</p>';
        if ($status['expires']) {
            echo '<p>' . esc_html(sprintf(
                /* translators: %s: expiry timestamp. */
                __('Expires: %s', 'nubivio-healthcare-security-hardening'),
                $status['expires']
            )) . '</p>';
        }
        echo '<p><a href="' . esc_url($this->core->canonical_url()) . '">' . esc_html($this->core->canonical_url()) . '</a></p>';

        // Recommendations.
        echo '<h2>' . esc_html__('Recommendations', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<ul>';
        echo '<li>' . esc_html__('Resolve HIGH findings first, then MEDIUM.', 'nubivio-healthcare-security-hardening') . '</li>';
        echo '<li>' . esc_html__('Enforce a Content-Security-Policy once tested in Report-Only.', 'nubivio-healthcare-security-hardening') . '</li>';
        echo '<li>' . esc_html__('Keep plugins, themes and WordPress core up to date.', 'nubivio-healthcare-security-hardening') . '</li>';
        echo '</ul>';

        // CRA deadline awareness.
        echo '<h2>' . esc_html__('CRA reporting deadlines (awareness)', 'nubivio-healthcare-security-hardening') . '</h2>';
        echo '<p class="muted">' . esc_html__('Under the CRA, actively exploited vulnerabilities require an early warning within 24 hours, a notification within 72 hours, and a final report within 14 days. This is awareness information, not legal advice.', 'nubivio-healthcare-security-hardening') . '</p>';

        echo $this->html_foot(); // phpcs:ignore WordPress.Security.EscapeOutput
    }

    private function band_label($band) {
        switch ($band) {
            case 'green':
                return __('Green', 'nubivio-healthcare-security-hardening');
            case 'amber':
                return __('Amber', 'nubivio-healthcare-security-hardening');
            default:
                return __('Red', 'nubivio-healthcare-security-hardening');
        }
    }
}
